### ISSUE TITLE
Reducing the number of layers

### ISSUE THREAD

**Issue by gllmflndn** [mtmiller/octave-snapshot#1]
Hi Mike,
Thanks for this - might be useful for testing purposes.
The Docker help recommends avoiding `RUN apt-get upgrade` and combining `RUN apt-get update` and `apt-get install`
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run
```
RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    build-essential \
    ...
```
This will also reduce the number of layers.

**Comment by mtmiller** [comment]
Thanks, I was going to look at rewriting using some best practices examples to strike a balance between reusability of layers and having too many layers. Appreciate the pointer to the best practices docs.

**Comment by mtmiller** [comment]
I think I've now combined as much as possible and followed the referenced best practices with 17f7087, fe2fc8f, and 6092b08. There should be far fewer layers now, and hopefully a lot less to download now.
